databaseType = "MySql"
id = "a1b1d097-bf0a-49ce-b183-d602dcdcd644"
name = "Librairie"

[flyway]
locations = ["filesystem:migrations"]
mixed = true
outOfOrder = true
validateMigrationNaming = true

[flyway.check]
majorTolerance = 0

[flywayDesktop]
developmentEnvironment = "development"
schemaModel = "schema-model"
shadowEnvironment = "shadow"

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.mysql.options.ignores]
ignoreNewlinesInTextObjects = "off"